const userEmail = prompt(" la tua email");

const emailArray = [
    'alice@example.com',
    'bob@example.com',
    'charlie@example.com',
    'david@example.com',
    'emma@example.com',
    'frank@example.com',
    'grace@example.com',
    'henry@example.com',
    'isabel@example.com',
    'jack@example.com',
    'kate@example.com',
    'leo@example.com',
    'maya@example.com',
    'nathan@example.com',
    'olivia@example.com',
    'peter@example.com',
    'quinn@example.com',
    'rachel@example.com',
    'sam@example.com',
    'tara@example.com',
    'ulysses@example.com',
    'violet@example.com',
    'winston@example.com',
    'xena@example.com',
    'yuri@example.com',
    'zara@example.com',
    'adam@example.com',
    'bella@example.com',
    'carter@example.com',
    'daisy@example.com',
    'elijah@example.com',
    'fiona@example.com',
    'gavin@example.com',
    'hannah@example.com',
    'ian@example.com',
    'jenna@example.com',
    'kevin@example.com',
    'lily@example.com',
    'mason@example.com',
    'nora@example.com',
    'oliver@example.com',
    'pam@example.com'
  ];
  
  console.log(emailArray);
  